#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("TestAppXamarinForms.Droid.Resource", IsApplication=true)]

namespace TestAppXamarinForms.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f090003
			public const int com_appboy_disable_location_collection = 2131296259;
			
			// aapt resource value: 0x7f090002
			public const int com_appboy_newsfeed_unread_visual_indicator_on = 2131296258;
			
			// aapt resource value: 0x7f090001
			public const int com_appboy_push_adm_messaging_registration_enabled = 2131296257;
			
			// aapt resource value: 0x7f090000
			public const int com_appboy_push_gcm_messaging_registration_enabled = 2131296256;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040022
			public const int com_appboy_button = 2130968610;
			
			// aapt resource value: 0x7f040000
			public const int com_appboy_button_disabled = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int com_appboy_button_enabled = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int com_appboy_card_background_border = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int com_appboy_card_background_shadow = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int com_appboy_card_title_container = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int com_appboy_cross_promotion_card_price = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int com_appboy_cross_promotion_card_review_count = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int com_appboy_cross_promotion_card_subtitle = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int com_appboy_cross_promotion_small_card_recommendation_tab_text = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int com_appboy_custom_notification_content = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int com_appboy_custom_notification_time = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int com_appboy_custom_notification_title = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int com_appboy_description = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int com_appboy_domain = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int com_appboy_feedback_form_background = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int com_appboy_feedback_form_is_bug = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int com_appboy_feedback_form_navigation_bar_background = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int com_appboy_inappmessage_background_dark = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int com_appboy_inappmessage_background_light = 2130968594;
			
			// aapt resource value: 0x7f040013
			public const int com_appboy_inappmessage_button_bg_light = 2130968595;
			
			// aapt resource value: 0x7f040014
			public const int com_appboy_inappmessage_button_close_light = 2130968596;
			
			// aapt resource value: 0x7f040015
			public const int com_appboy_inappmessage_button_text_light = 2130968597;
			
			// aapt resource value: 0x7f040016
			public const int com_appboy_inappmessage_chevron = 2130968598;
			
			// aapt resource value: 0x7f040017
			public const int com_appboy_inappmessage_header_text_light = 2130968599;
			
			// aapt resource value: 0x7f040018
			public const int com_appboy_inappmessage_icon = 2130968600;
			
			// aapt resource value: 0x7f040019
			public const int com_appboy_inappmessage_icon_background = 2130968601;
			
			// aapt resource value: 0x7f04001a
			public const int com_appboy_inappmessage_modal_frame_light = 2130968602;
			
			// aapt resource value: 0x7f04001b
			public const int com_appboy_inappmessage_text_dark = 2130968603;
			
			// aapt resource value: 0x7f04001c
			public const int com_appboy_inappmessage_text_light = 2130968604;
			
			// aapt resource value: 0x7f04001d
			public const int com_appboy_newsfeed_swipe_refresh_color_1 = 2130968605;
			
			// aapt resource value: 0x7f04001e
			public const int com_appboy_newsfeed_swipe_refresh_color_2 = 2130968606;
			
			// aapt resource value: 0x7f04001f
			public const int com_appboy_newsfeed_swipe_refresh_color_3 = 2130968607;
			
			// aapt resource value: 0x7f040020
			public const int com_appboy_newsfeed_swipe_refresh_color_4 = 2130968608;
			
			// aapt resource value: 0x7f040021
			public const int com_appboy_title = 2130968609;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public const int com_appboy_card_background_border_bottom = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int com_appboy_card_background_border_left = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int com_appboy_card_background_border_right = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int com_appboy_card_background_border_top = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int com_appboy_card_background_corner_radius = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int com_appboy_card_background_shadow_bottom = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int com_appboy_card_background_shadow_radius = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int com_appboy_feed_max_width = 2131034119;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int com_appboy_button = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int com_appboy_button_disabled = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int com_appboy_button_normal = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int com_appboy_button_pressed = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int com_appboy_card_background = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int com_appboy_cross_promotion_small_card_recommended_tab_background = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int com_appboy_icon_background = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int com_appboy_inappmessage_button_background = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int com_appboy_inappmessage_button_close = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int com_appboy_inappmessage_chevron = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int com_appboy_inappmessage_modal_background = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int com_appboy_rating_empty_star = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int com_appboy_rating_full_star = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int com_appboy_rating_half_star = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int icon = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int icon_read = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int icon_unread = 2130837520;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a000f
			public const int appboy_feed_swipe_container = 2131361807;
			
			// aapt resource value: 0x7f0a0001
			public const int com_appboy_banner_image_card_image = 2131361793;
			
			// aapt resource value: 0x7f0a0006
			public const int com_appboy_captioned_image_card_domain = 2131361798;
			
			// aapt resource value: 0x7f0a0002
			public const int com_appboy_captioned_image_card_image = 2131361794;
			
			// aapt resource value: 0x7f0a0003
			public const int com_appboy_captioned_image_card_title_container = 2131361795;
			
			// aapt resource value: 0x7f0a0005
			public const int com_appboy_captioned_image_description = 2131361797;
			
			// aapt resource value: 0x7f0a0004
			public const int com_appboy_captioned_image_title = 2131361796;
			
			// aapt resource value: 0x7f0a0008
			public const int com_appboy_cross_promotion_small_card_image = 2131361800;
			
			// aapt resource value: 0x7f0a0009
			public const int com_appboy_cross_promotion_small_card_price = 2131361801;
			
			// aapt resource value: 0x7f0a0007
			public const int com_appboy_cross_promotion_small_card_recommendation_tab = 2131361799;
			
			// aapt resource value: 0x7f0a000d
			public const int com_appboy_cross_promotion_small_card_review_count = 2131361805;
			
			// aapt resource value: 0x7f0a000c
			public const int com_appboy_cross_promotion_small_card_star_rating = 2131361804;
			
			// aapt resource value: 0x7f0a000b
			public const int com_appboy_cross_promotion_small_card_subtitle = 2131361803;
			
			// aapt resource value: 0x7f0a000a
			public const int com_appboy_cross_promotion_small_card_title = 2131361802;
			
			// aapt resource value: 0x7f0a0000
			public const int com_appboy_feed = 2131361792;
			
			// aapt resource value: 0x7f0a0013
			public const int com_appboy_feed_empty_feed = 2131361811;
			
			// aapt resource value: 0x7f0a0011
			public const int com_appboy_feed_loading_spinner = 2131361809;
			
			// aapt resource value: 0x7f0a0012
			public const int com_appboy_feed_network_error = 2131361810;
			
			// aapt resource value: 0x7f0a0010
			public const int com_appboy_feed_root = 2131361808;
			
			// aapt resource value: 0x7f0a0014
			public const int com_appboy_feed_transparent_full_bounds_container_view = 2131361812;
			
			// aapt resource value: 0x7f0a001d
			public const int com_appboy_feedback = 2131361821;
			
			// aapt resource value: 0x7f0a0018
			public const int com_appboy_feedback_cancel = 2131361816;
			
			// aapt resource value: 0x7f0a001b
			public const int com_appboy_feedback_email = 2131361819;
			
			// aapt resource value: 0x7f0a001c
			public const int com_appboy_feedback_is_bug = 2131361820;
			
			// aapt resource value: 0x7f0a001a
			public const int com_appboy_feedback_message = 2131361818;
			
			// aapt resource value: 0x7f0a0017
			public const int com_appboy_feedback_navigation_bar = 2131361815;
			
			// aapt resource value: 0x7f0a0016
			public const int com_appboy_feedback_root = 2131361814;
			
			// aapt resource value: 0x7f0a0019
			public const int com_appboy_feedback_send = 2131361817;
			
			// aapt resource value: 0x7f0a001e
			public const int com_appboy_inappmessage_full = 2131361822;
			
			// aapt resource value: 0x7f0a0023
			public const int com_appboy_inappmessage_full_button_layout = 2131361827;
			
			// aapt resource value: 0x7f0a0024
			public const int com_appboy_inappmessage_full_button_one = 2131361828;
			
			// aapt resource value: 0x7f0a0025
			public const int com_appboy_inappmessage_full_button_two = 2131361829;
			
			// aapt resource value: 0x7f0a0026
			public const int com_appboy_inappmessage_full_close_button = 2131361830;
			
			// aapt resource value: 0x7f0a0021
			public const int com_appboy_inappmessage_full_header_text = 2131361825;
			
			// aapt resource value: 0x7f0a001f
			public const int com_appboy_inappmessage_full_image = 2131361823;
			
			// aapt resource value: 0x7f0a0022
			public const int com_appboy_inappmessage_full_message = 2131361826;
			
			// aapt resource value: 0x7f0a0020
			public const int com_appboy_inappmessage_full_text_layout = 2131361824;
			
			// aapt resource value: 0x7f0a0028
			public const int com_appboy_inappmessage_modal = 2131361832;
			
			// aapt resource value: 0x7f0a002f
			public const int com_appboy_inappmessage_modal_button_layout = 2131361839;
			
			// aapt resource value: 0x7f0a0030
			public const int com_appboy_inappmessage_modal_button_one = 2131361840;
			
			// aapt resource value: 0x7f0a0031
			public const int com_appboy_inappmessage_modal_button_two = 2131361841;
			
			// aapt resource value: 0x7f0a0032
			public const int com_appboy_inappmessage_modal_close_button = 2131361842;
			
			// aapt resource value: 0x7f0a0027
			public const int com_appboy_inappmessage_modal_container = 2131361831;
			
			// aapt resource value: 0x7f0a002d
			public const int com_appboy_inappmessage_modal_header_text = 2131361837;
			
			// aapt resource value: 0x7f0a002b
			public const int com_appboy_inappmessage_modal_icon = 2131361835;
			
			// aapt resource value: 0x7f0a002a
			public const int com_appboy_inappmessage_modal_image = 2131361834;
			
			// aapt resource value: 0x7f0a0029
			public const int com_appboy_inappmessage_modal_image_layout = 2131361833;
			
			// aapt resource value: 0x7f0a002e
			public const int com_appboy_inappmessage_modal_message = 2131361838;
			
			// aapt resource value: 0x7f0a002c
			public const int com_appboy_inappmessage_modal_text_layout = 2131361836;
			
			// aapt resource value: 0x7f0a0033
			public const int com_appboy_inappmessage_slideup = 2131361843;
			
			// aapt resource value: 0x7f0a0038
			public const int com_appboy_inappmessage_slideup_chevron = 2131361848;
			
			// aapt resource value: 0x7f0a0036
			public const int com_appboy_inappmessage_slideup_icon = 2131361846;
			
			// aapt resource value: 0x7f0a0035
			public const int com_appboy_inappmessage_slideup_image = 2131361845;
			
			// aapt resource value: 0x7f0a0034
			public const int com_appboy_inappmessage_slideup_image_layout = 2131361844;
			
			// aapt resource value: 0x7f0a0037
			public const int com_appboy_inappmessage_slideup_message = 2131361847;
			
			// aapt resource value: 0x7f0a0015
			public const int com_appboy_newsfeed_item_read_indicator_image_switcher = 2131361813;
			
			// aapt resource value: 0x7f0a003d
			public const int com_appboy_notification_content = 2131361853;
			
			// aapt resource value: 0x7f0a003a
			public const int com_appboy_notification_icon = 2131361850;
			
			// aapt resource value: 0x7f0a003c
			public const int com_appboy_notification_time = 2131361852;
			
			// aapt resource value: 0x7f0a003b
			public const int com_appboy_notification_title = 2131361851;
			
			// aapt resource value: 0x7f0a0040
			public const int com_appboy_short_news_card_description = 2131361856;
			
			// aapt resource value: 0x7f0a0041
			public const int com_appboy_short_news_card_domain = 2131361857;
			
			// aapt resource value: 0x7f0a003e
			public const int com_appboy_short_news_card_image = 2131361854;
			
			// aapt resource value: 0x7f0a003f
			public const int com_appboy_short_news_card_title = 2131361855;
			
			// aapt resource value: 0x7f0a0043
			public const int com_appboy_text_announcement_card_description = 2131361859;
			
			// aapt resource value: 0x7f0a0044
			public const int com_appboy_text_announcement_card_domain = 2131361860;
			
			// aapt resource value: 0x7f0a0042
			public const int com_appboy_text_announcement_card_title = 2131361858;
			
			// aapt resource value: 0x7f0a0045
			public const int com_appboy_webview_activity_webview = 2131361861;
			
			// aapt resource value: 0x7f0a0039
			public const int status_bar_latest_event_content = 2131361849;
			
			// aapt resource value: 0x7f0a000e
			public const int tag = 2131361806;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f080000
			public const int com_appboy_data_flush_interval_bad_network = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int com_appboy_data_flush_interval_good_network = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int com_appboy_data_flush_interval_great_network = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int com_appboy_session_timeout = 2131230723;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int appboy_feed_layout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int com_appboy_banner_image_card = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int com_appboy_captioned_image_card = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int com_appboy_cross_promotion_small_card = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int com_appboy_default_card = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int com_appboy_feed = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int com_appboy_feed_activity = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int com_appboy_feed_footer = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int com_appboy_feed_header = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int com_appboy_feed_read_indicator_holder = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int com_appboy_feedback = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int com_appboy_feedback_activity = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int com_appboy_inappmessage_full = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int com_appboy_inappmessage_modal = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int com_appboy_inappmessage_slideup = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int com_appboy_notification = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int com_appboy_short_news_card = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int com_appboy_text_announcement_card = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int com_appboy_webview_activity = 2130903058;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060019
			public const int addSlideup = 2131099673;
			
			// aapt resource value: 0x7f06001b
			public const int app_name = 2131099675;
			
			// aapt resource value: 0x7f060012
			public const int changeUser = 2131099666;
			
			// aapt resource value: 0x7f06000f
			public const int com_appboy_api_key = 2131099663;
			
			// aapt resource value: 0x7f060000
			public const int com_appboy_feed_connection_error_body = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int com_appboy_feed_connection_error_title = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int com_appboy_feed_empty = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int com_appboy_feedback_form_cancel = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int com_appboy_feedback_form_email = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int com_appboy_feedback_form_empty_email = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int com_appboy_feedback_form_invalid_email = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int com_appboy_feedback_form_invalid_message = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int com_appboy_feedback_form_is_bug = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int com_appboy_feedback_form_message = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int com_appboy_feedback_form_send = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int com_appboy_notification_time_twelve_hour_format = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int com_appboy_notification_time_twenty_four_hour_format = 2131099660;
			
			// aapt resource value: 0x7f060011
			public const int com_appboy_push_gcm_sender_id = 2131099665;
			
			// aapt resource value: 0x7f06000d
			public const int com_appboy_recommendation_free = 2131099661;
			
			// aapt resource value: 0x7f060010
			public const int com_appboy_server_target = 2131099664;
			
			// aapt resource value: 0x7f06001a
			public const int dataFlush = 2131099674;
			
			// aapt resource value: 0x7f060014
			public const int eventsAndPurchases = 2131099668;
			
			// aapt resource value: 0x7f060018
			public const int launchFeedback = 2131099672;
			
			// aapt resource value: 0x7f060017
			public const int launchNewsFeed = 2131099671;
			
			// aapt resource value: 0x7f06000e
			public const int resource_for_package_identification = 2131099662;
			
			// aapt resource value: 0x7f060013
			public const int setUserProperties = 2131099667;
			
			// aapt resource value: 0x7f060015
			public const int submitFeedback = 2131099669;
			
			// aapt resource value: 0x7f060016
			public const int trackSocialData = 2131099670;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int Appboy = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int Appboy_Button = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int Appboy_Cards = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int Appboy_Cards_BannerImage = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int Appboy_Cards_BannerImage_Image = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int Appboy_Cards_CaptionedImage = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int Appboy_Cards_CaptionedImage_Description = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int Appboy_Cards_CaptionedImage_Domain = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int Appboy_Cards_CaptionedImage_Image = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int Appboy_Cards_CaptionedImage_Title = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int Appboy_Cards_CaptionedImage_Title_Container = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int Appboy_Cards_CrossPromotionSmall = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int Appboy_Cards_CrossPromotionSmall_Image = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int Appboy_Cards_CrossPromotionSmall_Layout = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int Appboy_Cards_CrossPromotionSmall_Price = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int Appboy_Cards_CrossPromotionSmall_RatingBar = 2131165199;
			
			// aapt resource value: 0x7f070010
			public const int Appboy_Cards_CrossPromotionSmall_RecommendationTab = 2131165200;
			
			// aapt resource value: 0x7f070011
			public const int Appboy_Cards_CrossPromotionSmall_ReviewCount = 2131165201;
			
			// aapt resource value: 0x7f070012
			public const int Appboy_Cards_CrossPromotionSmall_Subtitle = 2131165202;
			
			// aapt resource value: 0x7f070013
			public const int Appboy_Cards_CrossPromotionSmall_Title = 2131165203;
			
			// aapt resource value: 0x7f070014
			public const int Appboy_Cards_ShortNews = 2131165204;
			
			// aapt resource value: 0x7f070015
			public const int Appboy_Cards_ShortNews_Description = 2131165205;
			
			// aapt resource value: 0x7f070016
			public const int Appboy_Cards_ShortNews_Domain = 2131165206;
			
			// aapt resource value: 0x7f070017
			public const int Appboy_Cards_ShortNews_Image = 2131165207;
			
			// aapt resource value: 0x7f070018
			public const int Appboy_Cards_ShortNews_Title = 2131165208;
			
			// aapt resource value: 0x7f070019
			public const int Appboy_Cards_TextAnnouncement = 2131165209;
			
			// aapt resource value: 0x7f07001a
			public const int Appboy_Cards_TextAnnouncement_Description = 2131165210;
			
			// aapt resource value: 0x7f07001b
			public const int Appboy_Cards_TextAnnouncement_Domain = 2131165211;
			
			// aapt resource value: 0x7f07001c
			public const int Appboy_Cards_TextAnnouncement_Title = 2131165212;
			
			// aapt resource value: 0x7f07001d
			public const int Appboy_EventContent = 2131165213;
			
			// aapt resource value: 0x7f07001e
			public const int Appboy_EventContent_Time = 2131165214;
			
			// aapt resource value: 0x7f07001f
			public const int Appboy_EventContent_Title = 2131165215;
			
			// aapt resource value: 0x7f070020
			public const int Appboy_Feed = 2131165216;
			
			// aapt resource value: 0x7f070021
			public const int Appboy_Feed_Empty = 2131165217;
			
			// aapt resource value: 0x7f070022
			public const int Appboy_Feed_List = 2131165218;
			
			// aapt resource value: 0x7f070023
			public const int Appboy_Feed_NetworkErrorBody = 2131165219;
			
			// aapt resource value: 0x7f070024
			public const int Appboy_Feed_NetworkErrorTitle = 2131165220;
			
			// aapt resource value: 0x7f070025
			public const int Appboy_Feedback = 2131165221;
			
			// aapt resource value: 0x7f070026
			public const int Appboy_Feedback_EmailEditText = 2131165222;
			
			// aapt resource value: 0x7f070027
			public const int Appboy_Feedback_IsBugCheckBox = 2131165223;
			
			// aapt resource value: 0x7f070028
			public const int Appboy_Feedback_Layout = 2131165224;
			
			// aapt resource value: 0x7f070029
			public const int Appboy_Feedback_MessageEditText = 2131165225;
			
			// aapt resource value: 0x7f07002a
			public const int Appboy_Feedback_NavigationBar = 2131165226;
			
			// aapt resource value: 0x7f07002b
			public const int Appboy_Feedback_NavigationBarCancelButton = 2131165227;
			
			// aapt resource value: 0x7f07002c
			public const int Appboy_Feedback_NavigationBarSendButton = 2131165228;
			
			// aapt resource value: 0x7f07002d
			public const int Appboy_InAppMessage = 2131165229;
			
			// aapt resource value: 0x7f07002e
			public const int Appboy_InAppMessage_Button = 2131165230;
			
			// aapt resource value: 0x7f07002f
			public const int Appboy_InAppMessage_Button_Full = 2131165231;
			
			// aapt resource value: 0x7f070030
			public const int Appboy_InAppMessage_Button_Full_One = 2131165232;
			
			// aapt resource value: 0x7f070031
			public const int Appboy_InAppMessage_Button_Full_Two = 2131165233;
			
			// aapt resource value: 0x7f070032
			public const int Appboy_InAppMessage_Button_Modal = 2131165234;
			
			// aapt resource value: 0x7f070033
			public const int Appboy_InAppMessage_Button_Modal_One = 2131165235;
			
			// aapt resource value: 0x7f070034
			public const int Appboy_InAppMessage_Button_Modal_Two = 2131165236;
			
			// aapt resource value: 0x7f070035
			public const int Appboy_InAppMessage_Chevron = 2131165237;
			
			// aapt resource value: 0x7f070036
			public const int Appboy_InAppMessage_CloseButton = 2131165238;
			
			// aapt resource value: 0x7f070037
			public const int Appboy_InAppMessage_CloseButton_Full = 2131165239;
			
			// aapt resource value: 0x7f070038
			public const int Appboy_InAppMessage_CloseButton_Modal = 2131165240;
			
			// aapt resource value: 0x7f070039
			public const int Appboy_InAppMessage_Full = 2131165241;
			
			// aapt resource value: 0x7f07003a
			public const int Appboy_InAppMessage_Full_TextArea = 2131165242;
			
			// aapt resource value: 0x7f07003b
			public const int Appboy_InAppMessage_Full_TextArea_Landscape = 2131165243;
			
			// aapt resource value: 0x7f07003c
			public const int Appboy_InAppMessage_Full_TextArea_Portrait = 2131165244;
			
			// aapt resource value: 0x7f07003d
			public const int Appboy_InAppMessage_Header = 2131165245;
			
			// aapt resource value: 0x7f07003e
			public const int Appboy_InAppMessage_Header_Full = 2131165246;
			
			// aapt resource value: 0x7f07003f
			public const int Appboy_InAppMessage_Header_Modal = 2131165247;
			
			// aapt resource value: 0x7f070040
			public const int Appboy_InAppMessage_Icon = 2131165248;
			
			// aapt resource value: 0x7f070041
			public const int Appboy_InAppMessage_Icon_Modal = 2131165249;
			
			// aapt resource value: 0x7f070042
			public const int Appboy_InAppMessage_Icon_Slideup = 2131165250;
			
			// aapt resource value: 0x7f070043
			public const int Appboy_InAppMessage_Image = 2131165251;
			
			// aapt resource value: 0x7f070044
			public const int Appboy_InAppMessage_Image_Full = 2131165252;
			
			// aapt resource value: 0x7f070045
			public const int Appboy_InAppMessage_Image_Full_Landscape = 2131165253;
			
			// aapt resource value: 0x7f070046
			public const int Appboy_InAppMessage_Image_Full_Portrait = 2131165254;
			
			// aapt resource value: 0x7f070047
			public const int Appboy_InAppMessage_Image_Modal = 2131165255;
			
			// aapt resource value: 0x7f070048
			public const int Appboy_InAppMessage_Image_Slideup = 2131165256;
			
			// aapt resource value: 0x7f070049
			public const int Appboy_InAppMessage_Layout = 2131165257;
			
			// aapt resource value: 0x7f07004a
			public const int Appboy_InAppMessage_Layout_Button = 2131165258;
			
			// aapt resource value: 0x7f07004b
			public const int Appboy_InAppMessage_Layout_Button_Full = 2131165259;
			
			// aapt resource value: 0x7f07004c
			public const int Appboy_InAppMessage_Layout_Button_Modal = 2131165260;
			
			// aapt resource value: 0x7f07004d
			public const int Appboy_InAppMessage_Layout_Text = 2131165261;
			
			// aapt resource value: 0x7f07004e
			public const int Appboy_InAppMessage_Layout_Text_Full = 2131165262;
			
			// aapt resource value: 0x7f07004f
			public const int Appboy_InAppMessage_Layout_Text_Modal = 2131165263;
			
			// aapt resource value: 0x7f070050
			public const int Appboy_InAppMessage_Message = 2131165264;
			
			// aapt resource value: 0x7f070051
			public const int Appboy_InAppMessage_Message_Full = 2131165265;
			
			// aapt resource value: 0x7f070052
			public const int Appboy_InAppMessage_Message_Modal = 2131165266;
			
			// aapt resource value: 0x7f070053
			public const int Appboy_InAppMessage_Message_Slideup = 2131165267;
			
			// aapt resource value: 0x7f070054
			public const int Appboy_InAppMessage_Modal = 2131165268;
			
			// aapt resource value: 0x7f070055
			public const int Appboy_InAppMessage_Modal_Frame = 2131165269;
			
			// aapt resource value: 0x7f070056
			public const int Appboy_InAppMessage_Slideup = 2131165270;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
