#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("TestAppXamarinForms.Droid.Resource", IsApplication=true)]

namespace TestAppXamarinForms.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int appboyInAppMessageCustomFontFile = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f090003
			public const int com_appboy_disable_location_collection = 2131296259;
			
			// aapt resource value: 0x7f090002
			public const int com_appboy_newsfeed_unread_visual_indicator_on = 2131296258;
			
			// aapt resource value: 0x7f090001
			public const int com_appboy_push_adm_messaging_registration_enabled = 2131296257;
			
			// aapt resource value: 0x7f090000
			public const int com_appboy_push_gcm_messaging_registration_enabled = 2131296256;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f070022
			public const int com_appboy_button = 2131165218;
			
			// aapt resource value: 0x7f070000
			public const int com_appboy_button_disabled = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int com_appboy_button_enabled = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int com_appboy_card_background_border = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int com_appboy_card_background_shadow = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int com_appboy_card_title_container = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int com_appboy_cross_promotion_card_price = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int com_appboy_cross_promotion_card_review_count = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int com_appboy_cross_promotion_card_subtitle = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int com_appboy_cross_promotion_small_card_recommendation_tab_text = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int com_appboy_custom_notification_content = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int com_appboy_custom_notification_time = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int com_appboy_custom_notification_title = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int com_appboy_description = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int com_appboy_domain = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int com_appboy_feedback_form_background = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int com_appboy_feedback_form_is_bug = 2131165199;
			
			// aapt resource value: 0x7f070010
			public const int com_appboy_feedback_form_navigation_bar_background = 2131165200;
			
			// aapt resource value: 0x7f070011
			public const int com_appboy_inappmessage_background_dark = 2131165201;
			
			// aapt resource value: 0x7f070012
			public const int com_appboy_inappmessage_background_light = 2131165202;
			
			// aapt resource value: 0x7f070013
			public const int com_appboy_inappmessage_button_bg_light = 2131165203;
			
			// aapt resource value: 0x7f070014
			public const int com_appboy_inappmessage_button_close_light = 2131165204;
			
			// aapt resource value: 0x7f070015
			public const int com_appboy_inappmessage_button_text_light = 2131165205;
			
			// aapt resource value: 0x7f070016
			public const int com_appboy_inappmessage_chevron = 2131165206;
			
			// aapt resource value: 0x7f070017
			public const int com_appboy_inappmessage_header_text_light = 2131165207;
			
			// aapt resource value: 0x7f070018
			public const int com_appboy_inappmessage_icon = 2131165208;
			
			// aapt resource value: 0x7f070019
			public const int com_appboy_inappmessage_icon_background = 2131165209;
			
			// aapt resource value: 0x7f07001a
			public const int com_appboy_inappmessage_modal_frame_light = 2131165210;
			
			// aapt resource value: 0x7f07001b
			public const int com_appboy_inappmessage_text_dark = 2131165211;
			
			// aapt resource value: 0x7f07001c
			public const int com_appboy_inappmessage_text_light = 2131165212;
			
			// aapt resource value: 0x7f07001d
			public const int com_appboy_newsfeed_swipe_refresh_color_1 = 2131165213;
			
			// aapt resource value: 0x7f07001e
			public const int com_appboy_newsfeed_swipe_refresh_color_2 = 2131165214;
			
			// aapt resource value: 0x7f07001f
			public const int com_appboy_newsfeed_swipe_refresh_color_3 = 2131165215;
			
			// aapt resource value: 0x7f070020
			public const int com_appboy_newsfeed_swipe_refresh_color_4 = 2131165216;
			
			// aapt resource value: 0x7f070021
			public const int com_appboy_title = 2131165217;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public const int com_appboy_card_background_border_bottom = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int com_appboy_card_background_border_left = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int com_appboy_card_background_border_right = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int com_appboy_card_background_border_top = 2131034115;
			
			// aapt resource value: 0x7f050006
			public const int com_appboy_card_background_corner_radius = 2131034118;
			
			// aapt resource value: 0x7f050004
			public const int com_appboy_card_background_shadow_bottom = 2131034116;
			
			// aapt resource value: 0x7f050007
			public const int com_appboy_card_background_shadow_radius = 2131034119;
			
			// aapt resource value: 0x7f050005
			public const int com_appboy_feed_max_width = 2131034117;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int com_appboy_button = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int com_appboy_button_disabled = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int com_appboy_button_normal = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int com_appboy_button_pressed = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int com_appboy_card_background = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int com_appboy_cross_promotion_small_card_recommended_tab_background = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int com_appboy_ic_arrow_forward_white = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int com_appboy_ic_attach_money_white = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int com_appboy_ic_cancel_white = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int com_appboy_ic_check_circle_white = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int com_appboy_ic_check_white = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int com_appboy_ic_chevron_right_white = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int com_appboy_ic_close_white = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int com_appboy_ic_exit_to_app_white = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int com_appboy_ic_favorite_white = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int com_appboy_ic_grade_white = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int com_appboy_ic_highlight_off_white = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int com_appboy_ic_info_white = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int com_appboy_ic_language_white = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int com_appboy_ic_local_atm_white = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int com_appboy_ic_people_white = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int com_appboy_ic_phone_android_white = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int com_appboy_ic_place_white = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int com_appboy_ic_public_white = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int com_appboy_ic_schedule_white = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int com_appboy_ic_settings_white = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int com_appboy_ic_share_white = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int com_appboy_ic_shopping_cart_white = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int com_appboy_ic_thumb_down_white = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int com_appboy_ic_thumb_up_white = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int com_appboy_icon_background = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int com_appboy_inappmessage_button_background = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int com_appboy_inappmessage_button_close = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int com_appboy_inappmessage_chevron = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int com_appboy_inappmessage_modal_background = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int com_appboy_rating_empty_star = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int com_appboy_rating_full_star = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int com_appboy_rating_half_star = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int icon = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int icon_read = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int icon_unread = 2130837544;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a0014
			public const int appboy_feed_swipe_container = 2131361812;
			
			// aapt resource value: 0x7f0a0002
			public const int com_appboy_banner_image_card_drawee_stub = 2131361794;
			
			// aapt resource value: 0x7f0a0001
			public const int com_appboy_banner_image_card_imageview_stub = 2131361793;
			
			// aapt resource value: 0x7f0a0009
			public const int com_appboy_captioned_image_card_domain = 2131361801;
			
			// aapt resource value: 0x7f0a0005
			public const int com_appboy_captioned_image_card_drawee_stub = 2131361797;
			
			// aapt resource value: 0x7f0a0004
			public const int com_appboy_captioned_image_card_image = 2131361796;
			
			// aapt resource value: 0x7f0a0003
			public const int com_appboy_captioned_image_card_imageview_stub = 2131361795;
			
			// aapt resource value: 0x7f0a0006
			public const int com_appboy_captioned_image_card_title_container = 2131361798;
			
			// aapt resource value: 0x7f0a0008
			public const int com_appboy_captioned_image_description = 2131361800;
			
			// aapt resource value: 0x7f0a0007
			public const int com_appboy_captioned_image_title = 2131361799;
			
			// aapt resource value: 0x7f0a000d
			public const int com_appboy_cross_promotion_small_card_drawee_stub = 2131361805;
			
			// aapt resource value: 0x7f0a000b
			public const int com_appboy_cross_promotion_small_card_image = 2131361803;
			
			// aapt resource value: 0x7f0a000c
			public const int com_appboy_cross_promotion_small_card_imageview_stub = 2131361804;
			
			// aapt resource value: 0x7f0a000e
			public const int com_appboy_cross_promotion_small_card_price = 2131361806;
			
			// aapt resource value: 0x7f0a000a
			public const int com_appboy_cross_promotion_small_card_recommendation_tab = 2131361802;
			
			// aapt resource value: 0x7f0a0012
			public const int com_appboy_cross_promotion_small_card_review_count = 2131361810;
			
			// aapt resource value: 0x7f0a0011
			public const int com_appboy_cross_promotion_small_card_star_rating = 2131361809;
			
			// aapt resource value: 0x7f0a0010
			public const int com_appboy_cross_promotion_small_card_subtitle = 2131361808;
			
			// aapt resource value: 0x7f0a000f
			public const int com_appboy_cross_promotion_small_card_title = 2131361807;
			
			// aapt resource value: 0x7f0a0000
			public const int com_appboy_feed = 2131361792;
			
			// aapt resource value: 0x7f0a0018
			public const int com_appboy_feed_empty_feed = 2131361816;
			
			// aapt resource value: 0x7f0a0016
			public const int com_appboy_feed_loading_spinner = 2131361814;
			
			// aapt resource value: 0x7f0a0017
			public const int com_appboy_feed_network_error = 2131361815;
			
			// aapt resource value: 0x7f0a0015
			public const int com_appboy_feed_root = 2131361813;
			
			// aapt resource value: 0x7f0a0019
			public const int com_appboy_feed_transparent_full_bounds_container_view = 2131361817;
			
			// aapt resource value: 0x7f0a0022
			public const int com_appboy_feedback = 2131361826;
			
			// aapt resource value: 0x7f0a001d
			public const int com_appboy_feedback_cancel = 2131361821;
			
			// aapt resource value: 0x7f0a0020
			public const int com_appboy_feedback_email = 2131361824;
			
			// aapt resource value: 0x7f0a0021
			public const int com_appboy_feedback_is_bug = 2131361825;
			
			// aapt resource value: 0x7f0a001f
			public const int com_appboy_feedback_message = 2131361823;
			
			// aapt resource value: 0x7f0a001c
			public const int com_appboy_feedback_navigation_bar = 2131361820;
			
			// aapt resource value: 0x7f0a001b
			public const int com_appboy_feedback_root = 2131361819;
			
			// aapt resource value: 0x7f0a001e
			public const int com_appboy_feedback_send = 2131361822;
			
			// aapt resource value: 0x7f0a0023
			public const int com_appboy_inappmessage_full = 2131361827;
			
			// aapt resource value: 0x7f0a0029
			public const int com_appboy_inappmessage_full_button_layout = 2131361833;
			
			// aapt resource value: 0x7f0a002a
			public const int com_appboy_inappmessage_full_button_one = 2131361834;
			
			// aapt resource value: 0x7f0a002b
			public const int com_appboy_inappmessage_full_button_two = 2131361835;
			
			// aapt resource value: 0x7f0a002c
			public const int com_appboy_inappmessage_full_close_button = 2131361836;
			
			// aapt resource value: 0x7f0a0025
			public const int com_appboy_inappmessage_full_drawee_stub = 2131361829;
			
			// aapt resource value: 0x7f0a0027
			public const int com_appboy_inappmessage_full_header_text = 2131361831;
			
			// aapt resource value: 0x7f0a0024
			public const int com_appboy_inappmessage_full_imageview_stub = 2131361828;
			
			// aapt resource value: 0x7f0a0028
			public const int com_appboy_inappmessage_full_message = 2131361832;
			
			// aapt resource value: 0x7f0a0026
			public const int com_appboy_inappmessage_full_text_layout = 2131361830;
			
			// aapt resource value: 0x7f0a002d
			public const int com_appboy_inappmessage_html_full = 2131361837;
			
			// aapt resource value: 0x7f0a002e
			public const int com_appboy_inappmessage_html_full_webview = 2131361838;
			
			// aapt resource value: 0x7f0a0031
			public const int com_appboy_inappmessage_modal = 2131361841;
			
			// aapt resource value: 0x7f0a0039
			public const int com_appboy_inappmessage_modal_button_layout = 2131361849;
			
			// aapt resource value: 0x7f0a003a
			public const int com_appboy_inappmessage_modal_button_one = 2131361850;
			
			// aapt resource value: 0x7f0a003b
			public const int com_appboy_inappmessage_modal_button_two = 2131361851;
			
			// aapt resource value: 0x7f0a003c
			public const int com_appboy_inappmessage_modal_close_button = 2131361852;
			
			// aapt resource value: 0x7f0a002f
			public const int com_appboy_inappmessage_modal_container = 2131361839;
			
			// aapt resource value: 0x7f0a0034
			public const int com_appboy_inappmessage_modal_drawee_stub = 2131361844;
			
			// aapt resource value: 0x7f0a0030
			public const int com_appboy_inappmessage_modal_frame = 2131361840;
			
			// aapt resource value: 0x7f0a0037
			public const int com_appboy_inappmessage_modal_header_text = 2131361847;
			
			// aapt resource value: 0x7f0a0035
			public const int com_appboy_inappmessage_modal_icon = 2131361845;
			
			// aapt resource value: 0x7f0a0032
			public const int com_appboy_inappmessage_modal_image_layout = 2131361842;
			
			// aapt resource value: 0x7f0a0033
			public const int com_appboy_inappmessage_modal_imageview_stub = 2131361843;
			
			// aapt resource value: 0x7f0a0038
			public const int com_appboy_inappmessage_modal_message = 2131361848;
			
			// aapt resource value: 0x7f0a0036
			public const int com_appboy_inappmessage_modal_text_layout = 2131361846;
			
			// aapt resource value: 0x7f0a003d
			public const int com_appboy_inappmessage_slideup = 2131361853;
			
			// aapt resource value: 0x7f0a0043
			public const int com_appboy_inappmessage_slideup_chevron = 2131361859;
			
			// aapt resource value: 0x7f0a0040
			public const int com_appboy_inappmessage_slideup_drawee_stub = 2131361856;
			
			// aapt resource value: 0x7f0a0041
			public const int com_appboy_inappmessage_slideup_icon = 2131361857;
			
			// aapt resource value: 0x7f0a003e
			public const int com_appboy_inappmessage_slideup_image_layout = 2131361854;
			
			// aapt resource value: 0x7f0a003f
			public const int com_appboy_inappmessage_slideup_imageview_stub = 2131361855;
			
			// aapt resource value: 0x7f0a0042
			public const int com_appboy_inappmessage_slideup_message = 2131361858;
			
			// aapt resource value: 0x7f0a001a
			public const int com_appboy_newsfeed_item_read_indicator_image_switcher = 2131361818;
			
			// aapt resource value: 0x7f0a0048
			public const int com_appboy_notification_content = 2131361864;
			
			// aapt resource value: 0x7f0a0045
			public const int com_appboy_notification_icon = 2131361861;
			
			// aapt resource value: 0x7f0a0047
			public const int com_appboy_notification_time = 2131361863;
			
			// aapt resource value: 0x7f0a0046
			public const int com_appboy_notification_title = 2131361862;
			
			// aapt resource value: 0x7f0a004d
			public const int com_appboy_short_news_card_description = 2131361869;
			
			// aapt resource value: 0x7f0a004e
			public const int com_appboy_short_news_card_domain = 2131361870;
			
			// aapt resource value: 0x7f0a004b
			public const int com_appboy_short_news_card_drawee_stub = 2131361867;
			
			// aapt resource value: 0x7f0a0049
			public const int com_appboy_short_news_card_image = 2131361865;
			
			// aapt resource value: 0x7f0a004a
			public const int com_appboy_short_news_card_imageview_stub = 2131361866;
			
			// aapt resource value: 0x7f0a004c
			public const int com_appboy_short_news_card_title = 2131361868;
			
			// aapt resource value: 0x7f0a0050
			public const int com_appboy_stubbed_feed_drawee_view = 2131361872;
			
			// aapt resource value: 0x7f0a004f
			public const int com_appboy_stubbed_feed_drawee_view_parent = 2131361871;
			
			// aapt resource value: 0x7f0a0052
			public const int com_appboy_stubbed_feed_image_view = 2131361874;
			
			// aapt resource value: 0x7f0a0051
			public const int com_appboy_stubbed_feed_image_view_parent = 2131361873;
			
			// aapt resource value: 0x7f0a0054
			public const int com_appboy_stubbed_inappmessage_drawee_view = 2131361876;
			
			// aapt resource value: 0x7f0a0053
			public const int com_appboy_stubbed_inappmessage_drawee_view_parent = 2131361875;
			
			// aapt resource value: 0x7f0a0056
			public const int com_appboy_stubbed_inappmessage_image_view = 2131361878;
			
			// aapt resource value: 0x7f0a0055
			public const int com_appboy_stubbed_inappmessage_image_view_parent = 2131361877;
			
			// aapt resource value: 0x7f0a0058
			public const int com_appboy_text_announcement_card_description = 2131361880;
			
			// aapt resource value: 0x7f0a0059
			public const int com_appboy_text_announcement_card_domain = 2131361881;
			
			// aapt resource value: 0x7f0a0057
			public const int com_appboy_text_announcement_card_title = 2131361879;
			
			// aapt resource value: 0x7f0a005a
			public const int com_appboy_webview_activity_webview = 2131361882;
			
			// aapt resource value: 0x7f0a0044
			public const int status_bar_latest_event_content = 2131361860;
			
			// aapt resource value: 0x7f0a0013
			public const int tag = 2131361811;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f080000
			public const int com_appboy_data_flush_interval_bad_network = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int com_appboy_data_flush_interval_good_network = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int com_appboy_data_flush_interval_great_network = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int com_appboy_session_timeout = 2131230723;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int appboy_feed_layout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int com_appboy_banner_image_card = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int com_appboy_captioned_image_card = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int com_appboy_cross_promotion_small_card = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int com_appboy_default_card = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int com_appboy_feed = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int com_appboy_feed_activity = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int com_appboy_feed_footer = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int com_appboy_feed_header = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int com_appboy_feed_read_indicator_holder = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int com_appboy_feedback = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int com_appboy_feedback_activity = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int com_appboy_inappmessage_full = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int com_appboy_inappmessage_html_full = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int com_appboy_inappmessage_modal = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int com_appboy_inappmessage_slideup = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int com_appboy_notification = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int com_appboy_short_news_card = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int com_appboy_stubbed_feed_drawee_view = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int com_appboy_stubbed_feed_image_view = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int com_appboy_stubbed_inappmessage_drawee_view = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int com_appboy_stubbed_inappmessage_image_view = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int com_appboy_text_announcement_card = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int com_appboy_webview_activity = 2130903063;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040019
			public const int addSlideup = 2130968601;
			
			// aapt resource value: 0x7f04001b
			public const int app_name = 2130968603;
			
			// aapt resource value: 0x7f040012
			public const int changeUser = 2130968594;
			
			// aapt resource value: 0x7f04000f
			public const int com_appboy_api_key = 2130968591;
			
			// aapt resource value: 0x7f040000
			public const int com_appboy_feed_connection_error_body = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int com_appboy_feed_connection_error_title = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int com_appboy_feed_empty = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int com_appboy_feedback_form_cancel = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int com_appboy_feedback_form_email = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int com_appboy_feedback_form_empty_email = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int com_appboy_feedback_form_invalid_email = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int com_appboy_feedback_form_invalid_message = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int com_appboy_feedback_form_is_bug = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int com_appboy_feedback_form_message = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int com_appboy_feedback_form_send = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int com_appboy_notification_time_twelve_hour_format = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int com_appboy_notification_time_twenty_four_hour_format = 2130968588;
			
			// aapt resource value: 0x7f040011
			public const int com_appboy_push_gcm_sender_id = 2130968593;
			
			// aapt resource value: 0x7f04000d
			public const int com_appboy_recommendation_free = 2130968589;
			
			// aapt resource value: 0x7f040010
			public const int com_appboy_server_target = 2130968592;
			
			// aapt resource value: 0x7f04001a
			public const int dataFlush = 2130968602;
			
			// aapt resource value: 0x7f040014
			public const int eventsAndPurchases = 2130968596;
			
			// aapt resource value: 0x7f040018
			public const int launchFeedback = 2130968600;
			
			// aapt resource value: 0x7f040017
			public const int launchNewsFeed = 2130968599;
			
			// aapt resource value: 0x7f04000e
			public const int resource_for_package_identification = 2130968590;
			
			// aapt resource value: 0x7f040013
			public const int setUserProperties = 2130968595;
			
			// aapt resource value: 0x7f040015
			public const int submitFeedback = 2130968597;
			
			// aapt resource value: 0x7f040016
			public const int trackSocialData = 2130968598;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Appboy = 2131099648;
			
			// aapt resource value: 0x7f06002b
			public const int Appboy_Button = 2131099691;
			
			// aapt resource value: 0x7f06002c
			public const int Appboy_Cards = 2131099692;
			
			// aapt resource value: 0x7f06002d
			public const int Appboy_Cards_BannerImage = 2131099693;
			
			// aapt resource value: 0x7f06002e
			public const int Appboy_Cards_BannerImage_Image = 2131099694;
			
			// aapt resource value: 0x7f06002f
			public const int Appboy_Cards_CaptionedImage = 2131099695;
			
			// aapt resource value: 0x7f060030
			public const int Appboy_Cards_CaptionedImage_Description = 2131099696;
			
			// aapt resource value: 0x7f060031
			public const int Appboy_Cards_CaptionedImage_Domain = 2131099697;
			
			// aapt resource value: 0x7f060032
			public const int Appboy_Cards_CaptionedImage_Image = 2131099698;
			
			// aapt resource value: 0x7f060033
			public const int Appboy_Cards_CaptionedImage_Title = 2131099699;
			
			// aapt resource value: 0x7f060034
			public const int Appboy_Cards_CaptionedImage_Title_Container = 2131099700;
			
			// aapt resource value: 0x7f060035
			public const int Appboy_Cards_CrossPromotionSmall = 2131099701;
			
			// aapt resource value: 0x7f060036
			public const int Appboy_Cards_CrossPromotionSmall_Image = 2131099702;
			
			// aapt resource value: 0x7f060037
			public const int Appboy_Cards_CrossPromotionSmall_Layout = 2131099703;
			
			// aapt resource value: 0x7f060038
			public const int Appboy_Cards_CrossPromotionSmall_Price = 2131099704;
			
			// aapt resource value: 0x7f060039
			public const int Appboy_Cards_CrossPromotionSmall_RatingBar = 2131099705;
			
			// aapt resource value: 0x7f06003a
			public const int Appboy_Cards_CrossPromotionSmall_RecommendationTab = 2131099706;
			
			// aapt resource value: 0x7f06003b
			public const int Appboy_Cards_CrossPromotionSmall_ReviewCount = 2131099707;
			
			// aapt resource value: 0x7f06003c
			public const int Appboy_Cards_CrossPromotionSmall_Subtitle = 2131099708;
			
			// aapt resource value: 0x7f06003d
			public const int Appboy_Cards_CrossPromotionSmall_Title = 2131099709;
			
			// aapt resource value: 0x7f06003e
			public const int Appboy_Cards_ShortNews = 2131099710;
			
			// aapt resource value: 0x7f06003f
			public const int Appboy_Cards_ShortNews_Description = 2131099711;
			
			// aapt resource value: 0x7f060040
			public const int Appboy_Cards_ShortNews_Domain = 2131099712;
			
			// aapt resource value: 0x7f060041
			public const int Appboy_Cards_ShortNews_Image = 2131099713;
			
			// aapt resource value: 0x7f060042
			public const int Appboy_Cards_ShortNews_Title = 2131099714;
			
			// aapt resource value: 0x7f060043
			public const int Appboy_Cards_TextAnnouncement = 2131099715;
			
			// aapt resource value: 0x7f060044
			public const int Appboy_Cards_TextAnnouncement_Description = 2131099716;
			
			// aapt resource value: 0x7f060045
			public const int Appboy_Cards_TextAnnouncement_Domain = 2131099717;
			
			// aapt resource value: 0x7f060046
			public const int Appboy_Cards_TextAnnouncement_Title = 2131099718;
			
			// aapt resource value: 0x7f060047
			public const int Appboy_EventContent = 2131099719;
			
			// aapt resource value: 0x7f060048
			public const int Appboy_EventContent_Time = 2131099720;
			
			// aapt resource value: 0x7f060049
			public const int Appboy_EventContent_Title = 2131099721;
			
			// aapt resource value: 0x7f06004a
			public const int Appboy_Feed = 2131099722;
			
			// aapt resource value: 0x7f06004b
			public const int Appboy_Feed_Empty = 2131099723;
			
			// aapt resource value: 0x7f06004c
			public const int Appboy_Feed_List = 2131099724;
			
			// aapt resource value: 0x7f06004d
			public const int Appboy_Feed_NetworkErrorBody = 2131099725;
			
			// aapt resource value: 0x7f06004e
			public const int Appboy_Feed_NetworkErrorTitle = 2131099726;
			
			// aapt resource value: 0x7f06004f
			public const int Appboy_Feedback = 2131099727;
			
			// aapt resource value: 0x7f060050
			public const int Appboy_Feedback_EmailEditText = 2131099728;
			
			// aapt resource value: 0x7f060051
			public const int Appboy_Feedback_IsBugCheckBox = 2131099729;
			
			// aapt resource value: 0x7f060052
			public const int Appboy_Feedback_Layout = 2131099730;
			
			// aapt resource value: 0x7f060053
			public const int Appboy_Feedback_MessageEditText = 2131099731;
			
			// aapt resource value: 0x7f060054
			public const int Appboy_Feedback_NavigationBar = 2131099732;
			
			// aapt resource value: 0x7f060055
			public const int Appboy_Feedback_NavigationBarCancelButton = 2131099733;
			
			// aapt resource value: 0x7f060056
			public const int Appboy_Feedback_NavigationBarSendButton = 2131099734;
			
			// aapt resource value: 0x7f060001
			public const int Appboy_InAppMessage = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int Appboy_InAppMessage_Button = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int Appboy_InAppMessage_Button_Full = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int Appboy_InAppMessage_Button_Full_One = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int Appboy_InAppMessage_Button_Full_Two = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int Appboy_InAppMessage_Button_Modal = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int Appboy_InAppMessage_Button_Modal_One = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int Appboy_InAppMessage_Button_Modal_Two = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int Appboy_InAppMessage_Chevron = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int Appboy_InAppMessage_CloseButton = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int Appboy_InAppMessage_CloseButton_Full = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int Appboy_InAppMessage_CloseButton_Modal = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int Appboy_InAppMessage_Full = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int Appboy_InAppMessage_Full_TextArea = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int Appboy_InAppMessage_Full_TextArea_Landscape = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int Appboy_InAppMessage_Full_TextArea_Portrait = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int Appboy_InAppMessage_Header = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int Appboy_InAppMessage_Header_Full = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int Appboy_InAppMessage_Header_Modal = 2131099667;
			
			// aapt resource value: 0x7f060057
			public const int Appboy_InAppMessage_Html = 2131099735;
			
			// aapt resource value: 0x7f060058
			public const int Appboy_InAppMessage_Html_Webview = 2131099736;
			
			// aapt resource value: 0x7f060014
			public const int Appboy_InAppMessage_Icon = 2131099668;
			
			// aapt resource value: 0x7f060015
			public const int Appboy_InAppMessage_Icon_Modal = 2131099669;
			
			// aapt resource value: 0x7f060016
			public const int Appboy_InAppMessage_Icon_Slideup = 2131099670;
			
			// aapt resource value: 0x7f060017
			public const int Appboy_InAppMessage_Image = 2131099671;
			
			// aapt resource value: 0x7f060018
			public const int Appboy_InAppMessage_Image_Full = 2131099672;
			
			// aapt resource value: 0x7f060019
			public const int Appboy_InAppMessage_Image_Full_Landscape = 2131099673;
			
			// aapt resource value: 0x7f06001a
			public const int Appboy_InAppMessage_Image_Full_Portrait = 2131099674;
			
			// aapt resource value: 0x7f06001b
			public const int Appboy_InAppMessage_Image_Modal = 2131099675;
			
			// aapt resource value: 0x7f06001c
			public const int Appboy_InAppMessage_Image_Slideup = 2131099676;
			
			// aapt resource value: 0x7f06001d
			public const int Appboy_InAppMessage_Layout = 2131099677;
			
			// aapt resource value: 0x7f06001e
			public const int Appboy_InAppMessage_Layout_Button = 2131099678;
			
			// aapt resource value: 0x7f06001f
			public const int Appboy_InAppMessage_Layout_Button_Full = 2131099679;
			
			// aapt resource value: 0x7f060020
			public const int Appboy_InAppMessage_Layout_Button_Modal = 2131099680;
			
			// aapt resource value: 0x7f060021
			public const int Appboy_InAppMessage_Layout_Text = 2131099681;
			
			// aapt resource value: 0x7f060022
			public const int Appboy_InAppMessage_Layout_Text_Full = 2131099682;
			
			// aapt resource value: 0x7f060023
			public const int Appboy_InAppMessage_Layout_Text_Modal = 2131099683;
			
			// aapt resource value: 0x7f060024
			public const int Appboy_InAppMessage_Message = 2131099684;
			
			// aapt resource value: 0x7f060025
			public const int Appboy_InAppMessage_Message_Full = 2131099685;
			
			// aapt resource value: 0x7f060026
			public const int Appboy_InAppMessage_Message_Modal = 2131099686;
			
			// aapt resource value: 0x7f060027
			public const int Appboy_InAppMessage_Message_Slideup = 2131099687;
			
			// aapt resource value: 0x7f060028
			public const int Appboy_InAppMessage_Modal = 2131099688;
			
			// aapt resource value: 0x7f060029
			public const int Appboy_InAppMessage_Modal_Frame = 2131099689;
			
			// aapt resource value: 0x7f06002a
			public const int Appboy_InAppMessage_Slideup = 2131099690;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] com_appboy_ui_inappmessage_AppboyInAppMessageButtonView = new int[]
			{
					2130771968};
			
			// aapt resource value: 0
			public const int com_appboy_ui_inappmessage_AppboyInAppMessageButtonView_appboyInAppMessageCustomFontFile = 0;
			
			public static int[] com_appboy_ui_inappmessage_AppboyInAppMessageTextView = new int[]
			{
					2130771968};
			
			// aapt resource value: 0
			public const int com_appboy_ui_inappmessage_AppboyInAppMessageTextView_appboyInAppMessageCustomFontFile = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
